
name: CMEMS model workflow

on:
  # triggered on push to repo
  # push:
  #   branches: dev
  # triggered by cron job
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.cronhub.io
    - cron:  '30 15 * * *'  #scheduled to run at 3:30 pm UTC every day
  # triggered by manual activation on GitHub repo website
  workflow_dispatch:

jobs:
  download_cmems:
    runs-on: ubuntu-24.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
      COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        sparse-checkout: |
          metadata/
          repo_cleanup/
          data_acquisition/R/
          data_acquisition/netcdfs/cmems_ncdfs/placeholder.txt
        sparse-checkout-cone-mode: false # Set to false for more granular control
    
    # - name: Print dir tree
    #   run: tree

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v4
      with:
        auto-update-conda: true
        channels: conda-forge,defaults
        python-version: 3.12
        activate-environment: test

    # - name: Check disk space
    #   run: |
    #     df -h

    - name: Install Copernicus Marine Toolbox
      shell: bash -el {0}
      run: |
        conda install -c conda-forge copernicusmarine scipy

    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.2'

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: always
    
    - name: Delete old CMEMS data
      shell: Rscript {0}
      run: |
        source("repo_cleanup/delete_old_cmems_files.R")
    
    - name: Prefer IPv4 over IPv6
      run: sudo sh -c "echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf"


    - name: Download CMEMS data
      timeout-minutes: 30
      shell: Rscript {0}
      run: source("data_acquisition/R/acquire_cmems.R")
    
    - name: Create artifact to share data with next job
      uses: actions/upload-artifact@v7
      with:
        name: raw_cmems
        path: data_acquisition/netcdfs/cmems_ncdfs/
        retention-days: 1

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # git fetch origin gh-pages --depth=1
        # git pull
        git add --sparse data_acquisition/netcdfs/cmems_ncdfs/*.nc
        git commit -m 'Added new CMEMS files'
        
        #Quickly fetches remote changes and reapplies local commit on top of it
        git pull --rebase
        git push

  process_cmems:
    runs-on: ubuntu-latest
    needs: download_cmems
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # Crucial: This allows the job to request the OIDC token for GCS Auth
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        sparse-checkout: |
          requirements.txt
          metadata/
          data_processing/R/
          data_acquisition/netcdfs/cmems_ncdfs/placeholder.txt
          data_processing/TopPredatorWatch/rasters/placeholder.txt
          data_processing/TopPredatorWatch/static/
        sparse-checkout-cone-mode: false # Set to false for more granular control

    - name: Download artifact w raw CMEMS files
      uses: actions/download-artifact@v8
      with:
        name: raw_cmems
        path: data_acquisition/netcdfs/cmems_ncdfs/
    
    - name: Print dir tree
      run: tree
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.2'

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: always

    - name: Process CMEMS netCDFs and created derived vars
      shell: Rscript {0}
      run: |
        source("data_processing/R/process_cmems.R")
      working-directory: ${{ github.workspace }}
    
    - name: Create artifact to share data with next job
      uses: actions/upload-artifact@v7
      with:
        name: processed_cmems
        path: data_processing/TopPredatorWatch/rasters/
        retention-days: 1
    
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v3'
      with:
        # You'll get these strings after setting up WIF in the GCP Console
        workload_identity_provider: 'projects/933817670224/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'ce-github-sa1@ggn-nmfs-usamlr-dev-7b99.iam.gserviceaccount.com'
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      shell: bash -el {0}
      run: python data_processing/R/append_cmems_zarr.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # git fetch origin gh-pages --depth=1
        # git pull
        
        git add --sparse data_processing/TopPredatorWatch/rasters/*.{nc,tiff}
        git commit -m 'Processed CMEMS files'
        
        #Quickly fetches remote changes and reapplies local commit on top of it
        git pull --rebase
        git push

  predict_TopPred:
    runs-on: ubuntu-latest
    needs: process_cmems
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        sparse-checkout: |
          metadata/
          model_prediction/R/
          data_processing/TopPredatorWatch/rasters/placeholder.txt
          model_prediction/TopPredatorWatch/
        sparse-checkout-cone-mode: true  # Set to false for more granular control

    # - name: Pull in Latest Changes
    #   run: |
    #     git config --global user.name "${{ github.actor }}"
    #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    # 
    #     git pull

    - name: List all files in directory before downloading artifact
      run: |
        tree
    
    - name: Download artifact w processed CMEMS files
      uses: actions/download-artifact@v8
      with:
        name: processed_cmems
        path: data_processing/TopPredatorWatch/rasters/
    
    - name: Print dir tree
      run: tree

    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.2'

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: always
        extra-packages:
          ropensci/rnaturalearthhires

    # - name: Install rnaturalearthhires R package from GitHub
    #   shell: Rscript {0}
    #   run: |
    #     install.packages("remotes")
    #     remotes::install_github("ropensci/rnaturalearthhires")

    - name: Make predictions for Top Predator Watch
      shell: Rscript {0}
      run: |
        source("model_prediction/R/predict_TopPredatorWatch.R")
      working-directory: ${{ github.workspace }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # git fetch origin gh-pages --depth=1
        # git pull
        
        git add --sparse model_prediction/TopPredatorWatch/*/
        git commit -m 'Made predictions for Top Predator Watch'
        
        #Quickly fetches remote changes and reapplies local commit on top of it
        git pull --rebase
        git push

