
name: Predict from ROMS tool

on:
  # triggered by previous GHA completion in workflow
  workflow_run:
    workflows: ["Process ROMS data"]
    types:
      - completed
  # triggered on push to repo
  # push:
  #   branches: main
  # triggered by cron job
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # https://crontab.cronhub.io
  #   - cron:  '30 15 * * *'  #scheduled to run at 3:30 pm UTC every day
  # triggered by manual activation on GitHub repo website
  workflow_dispatch:

jobs:
  predict-ROMS:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.3'

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 4

    - name: Install rnaturalearthhires R package from GitHub
      shell: Rscript {0}
      run: |
        remotes::install_github("ropensci/rnaturalearthhires")

    - name: Make predictions for ROMS tool
      shell: Rscript {0}
      run: |
        source("model_prediction/R/predict_ROMS.R")
      working-directory: ${{ github.workspace }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git add .
        git commit -m 'Made predictions for ROMS tool'
        git push
