
name: Test Zarr

on: 
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

jobs:
  read_zarr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # Crucial: This allows the job to request the OIDC token
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        # ref: 'dev'
        sparse-checkout: |
          requirements.txt
          data_processing/R/
        sparse-checkout-cone-mode: false # Set to false for more granular control
    
    # - name: Print dir tree
    #   run: tree

    # - name: Install Conda
    #   uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-update-conda: true
    #     channels: conda-forge,defaults
    #     python-version: 3.12

    # - name: Check disk space
    #   run: |
    #     df -h

    # - name: Install Copernicus Marine Toolbox
    #   shell: bash -el {0}
    #   run: |
    #     conda install -c conda-forge copernicusmarine xarray gcsfs zarr scipy
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    # - name: Create GCS Credentials File
    #   run: echo '${{ secrets.GCS_KEY }}' > ./gcs_key.json
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        # You'll get these strings after setting up WIF in the GCP Console
        workload_identity_provider: 'projects/933817670224/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'ce-github-sa1@ggn-nmfs-usamlr-dev-7b99.iam.gserviceaccount.com'

    - name: Run Python script
      shell: bash -el {0}
      run: python data_processing/R/test_zarr.py